
                                               -- ROLES
create table if not exists roles (
id int generated by default as identity not null primary key,
role varchar(15) not null unique
);

                                                -- USERS
create table if not exists users (
id int generated by default as identity not null primary key,
name varchar(100) not null,
phone_number varchar(20) not null unique,
password varchar(255) not null
);

                                            -- USERS_ROLES
create table if not exists users_roles (
user_id int not null references users(id) on delete cascade,
role_id int not null references roles(id) on delete cascade,
primary key (user_id, role_id)
);

                                            -- APPLICATIONS
create table if not exists applications (
id int generated by default as identity not null primary key,
description varchar(1000) not null,
phone_number varchar(20) not null,
name varchar(100) not null,
creators_id int not null references users(id) on delete cascade,
status varchar(20) not null default 'DRAFT',
create_date timestamp not null
);
