-- liquibase formatted sql

-- changeset liquibase:4

create table if not exists phone_details (
id int generated by default as identity not null primary key,
phone varchar(50) not null,
country_code varchar(5),
city_code varchar(5),
number varchar(10),
provider varchar(100),
country varchar(50),
region varchar(100)
);